[phases.setup]
nixPkgs = ['nodejs', 'bun']

[phases.install]
cmds = ['bun install']

[phases.build]
cmds = ['bun run build']

[start]
cmd = 'node node_modules/vite/bin/vite.js preview --host 0.0.0.0 --port $PORT'
